# Generated by Django 3.2 on 2021-04-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_news_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publication_data',
            new_name='publication_date',
        ),
    ]
