# Generated by Django 3.2 on 2021-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
