# Generated by Django 3.2 on 2021-04-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_alter_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='view_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
