# Generated by Django 3.2 on 2021-04-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_menuitem_view_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='view_name',
        ),
    ]
